package com.vlocity.deploymentTools.client;

/**
 * Created by Derek on 04/07/2016.
 */
public enum ArtifactTypeEnum {
    OMNISCRIPT,
    ELEMENT,
    COMPILED_OUTPUT,
    DATARAPTOR,
    CALCULATION_MATRIX,
    CALCULATION_MATRIX_ROW,
    CALCULATION_MATRIX_VERSION,
    CARD,
    APPLICATION_TEMPLATE,
    PRODUCT,
    ATTRIBUTE_ASSIGNMENT,
    REQUIRED_DOCUMENT,
    PRODUCT_DOCUMENT,
    ACTION,
    PARTY_RELATIONSHIP_TYPE
}
